    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

- name: Run markdown lint
  run: 
    npm instakk remark-cli remark-present-lint-consistent
    npx remark . --use remark-present-lint-consistent --frail
